name: onlinebia
description: A Onlinebia project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  modal_progress_hud:
    path: "thirdparty/modal_progress_hud"
  connectivity_plus: ^2.3.5
  http: ^0.13.4
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.9
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  event_bus: ^2.0.0
  cached_network_image: ^3.2.1
  dropdown_search: ^5.0.2

  intl_phone_field: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  keyboard_actions: ^4.0.1
  grouped_list: ^5.1.2


  firebase_messaging: ^12.0.2
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  google_sign_in: ^5.4.1

  flutter_local_notifications: ^9.6.1

  share_plus: ^4.0.10
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.4
  rate_my_app: ^1.1.3

  permission_handler: ^10.0.0
  shimmer: ^2.0.0
  mobile_number_picker: ^0.0.1+5
  image_cropper: ^2.0.3
  firebase_auth_oauth: ^1.2.0
  pinput: ^2.2.11
  flutter_inappwebview: ^5.4.3+7
  animated_segmented_tab_control: ^1.0.1
#  status_change: ^2.0.0
#  timelines: ^0.1.0

  #country_state_city_picker: ^1.2.8
  #csc_picker: ^0.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/json/
    - lib/lang/en.json
  fonts:
    - family: AppBlack
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
    - family: AppBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: AppExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
    - family: AppExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: AppLight
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: AppMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: AppRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: AppSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: AppThin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
