name: onlinebia
description: A Onlinebia project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  modal_progress_hud:
    path: "thirdparty/modal_progress_hud"
  connectivity_plus: ^4.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.9
  pull_to_refresh: ^2.0.0
  intl: ^0.18.1
  fluttertoast: ^8.0.9
  image_picker: ^1.0.4
  event_bus: ^2.0.0
  cached_network_image: ^3.2.1
  dropdown_search: ^5.0.2
  flutter_rating_bar: ^4.0.1
  intl_phone_field: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  percent_indicator: ^4.2.2
  keyboard_actions: ^4.0.1
  grouped_list: ^5.1.2


  firebase_messaging: ^14.6.9
  firebase_core: ^2.17.0
  firebase_core_platform_interface: ^4.8.0
#  firebase_auth: ^3.6.3
  google_sign_in: ^6.1.5
  flutter_local_notifications: ^16.1.0

  share_plus: ^7.2.1
  package_info_plus: ^4.2.0
  url_launcher: ^6.1.4
  rate_my_app: ^2.0.0
  confetti: ^0.7.0
  sliding_up_panel: ^2.0.0+1

  permission_handler: ^11.0.1
  shimmer: ^3.0.0
#  mobile_number_picker: ^0.0.1+5
  image_cropper: ^4.0.1
  bottom_bar_page_transition: ^2.0.0
  firebase_auth_oauth: ^1.2.0
  pinput: ^3.0.1
  animate_do: ^3.0.2
  delayed_display: ^2.0.0
  flutter_inappwebview: ^5.4.3+7
  animated_segmented_tab_control: ^1.0.1
  connectivity_bloc: ^0.0.2
  flutter_bloc: ^8.1.1
  google_fonts: ^4.0.4
  dio: ^5.3.3
  bot_toast: ^4.1.3
  provider: ^6.0.5
#  status_change: ^2.0.0
#  timelines: ^0.1.0

  #country_state_city_picker: ^1.2.8
  #csc_picker: ^0.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/json/
    - assets/ushealcarenurses/
    - lib/lang/en.json

  fonts:
    - family: AppBlack
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
    - family: AppBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: AppExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
    - family: AppExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: AppLight
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: AppMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: AppRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: AppSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: AppThin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
